<?xml version="1.0"?>
<robot name="differential_drive_robot" xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!-- Material and colors -->
     <material name="blue">
        <color rgba="0 0 1 1"/>
     </material>
     
     <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
     </material>

    <!--Body dimensions -->
    <xacro:property name="body_link_x_dim" value="0.8"/> 
    <xacro:property name="body_link_y_dim" value="0.6"/> 
    <xacro:property name="body_link_z_dim" value="0.3"/>

    <!-- Wheel dimensions -->
    <xacro:property name="wheel_link_radius" value="0.1"/> 
    <xacro:property name="wheel_link_length" value="0.07"/>
    <xacro:property name="wheel_link_z_location" value="-0.1"/>

    <!-- Material density -->

    <xacro:property name="body_density" value="2710.0"/>
    <xacro:property name="wheel_density" value="2710.0"/>

    <!-- pi density -->
    <xacro:property name="pi_const" value="3.14"/>

    <!-- Robot body and wheel mass --> 

    <xacro:property name="body_mass" 
    value="${body_density*body_link_x_dim*body_link_y_dim*body_link_z_dim}"/>

    <xacro:property name="wheel_mass" 
    value="${wheel_density*pi_const*wheel_link_radius*wheel_link_radius*wheel_link_length}"/>


    <!-- Moments of inertia of the wheel -->
    <xacro:property name="Iz_wheel" 
    value="${0.5*wheel_mass*wheel_link_radius*wheel_link_radius}" />
    <xacro:property name="I_wheel" 
    value="${(1.0/12.0)*wheel_mass*(3.0*wheel_link_radius*wheel_link_radius+wheel_link_length*wheel_link_length)}" />

    <!--This macro defines the complete inertial section of the wheel -->
    <!-- It is used later in the code --> 

    <xacro:macro name="inertia_wheel">
        <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="${I_wheel}" ixy="0.0" ixz="0.0" iyy="${I_wheel}" iyz="0" izz="${Iz_wheel}" />
        </inertial>
    </xacro:macro> 

    <!--.gazebo file-->
    <xacro:include filename="$(find patrol_bot)/model/robot.gazebo" />

    <link name="base_footprint">
    </link>

    <!--base -->

    <joint name="base_joint" type="fixed">       
        <parent link="base_footprint"/>
        <child link="body_link"/>
        <!--<origin xyz="0 0 0.1" rpy="0 0 0" /> -->
    </joint> 
    <link name="body_link">
        <visual>
            <geometry>
                <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}" />
            </geometry>
            <material name="grey" />
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <!-- can add material for bot-->
        </visual>

        <collision> 
            <geometry>
                <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}" />
            </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <!-- copy pasted form visual-->
        </collision>

        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="${body_mass}"/>
        <inertia
        ixx="${(1/12)*body_mass*(body_link_y_dim*body_link_y_dim+body_link_z_dim*body_link_z_dim)}"
        ixy="0" ixz="0" iyy="${(1/12)*body_mass*(body_link_x_dim*body_link_x_dim+body_link_z_dim*body_link_z_dim)}"
        iyz="0"
        izz="${(1/12)*body_mass*(body_link_y_dim*body_link_y_dim+body_link_x_dim*body_link_x_dim)}"/>
        </inertial>
    </link>
    

    <!--right back wheel-->

    <joint name="wheel1_joint" type="continuous">
        <parent link="body_link"/>
        <child link="wheel1_link" />
        <origin xyz="${-body_link_x_dim/2+1.2*wheel_link_radius} ${-body_link_y_dim/2-wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
        <limit effort="1000" velocity="1000"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>
    <link name="wheel1_link">
        <visual>
            <origin rpy="1.570795 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
            <material name="blue" />
        </visual>

        <collision>
            <origin rpy="1.570795 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
        </collision>
        <xacro:inertia_wheel />
    </link>

    <!--left back wheel-->

    <joint name="wheel2_joint" type="continuous" >
        <parent link="body_link"/>
        <child link="wheel2_link" />
        <origin xyz="${-body_link_x_dim/2+1.2*wheel_link_radius} ${body_link_y_dim/2+wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
        <limit effort="1000" velocity="1000"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>
    <link name="wheel2_link">
        <visual>
            <origin rpy="1.570795 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
            <material name="blue" />
        </visual>

        <collision>
            <origin rpy="1.570795 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
        </collision>
        <xacro:inertia_wheel />
    </link>

    <!--right front wheel-->

    <joint name="wheel3_joint" type="continuous" >
        <parent link="body_link"/>
        <child link="wheel3_link" />
        <origin xyz="${body_link_x_dim/2-1.2*wheel_link_radius} ${-body_link_y_dim/2-wheel_link_length/2} ${wheel_link_z_location}" />
        <axis xyz="0 1 0"/>
        <limit effort="1000" velocity="1000" />
        <dynamics damping="1.0" friction="1.0"/>
    </joint>
    <link name="wheel3_link">
        <visual>
            <origin rpy="1.570795 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
            <material name="blue" />
        </visual>

        <collision>
            <origin rpy="1.570795 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
        </collision>
        <xacro:inertia_wheel />
    </link>

    <!--left front wheel -->

    <joint name="wheel4_joint" type="continuous" >
        <parent link="body_link" />
        <child link="wheel4_link" />
        <origin xyz="${body_link_x_dim/2-1.2*wheel_link_radius} ${body_link_y_dim/2+wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
        <limit effort="1000" velocity="1000"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>
    <link name="wheel4_link">
        <visual>
            <origin rpy="1.570795 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <origin rpy="1.570795 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
        </collision>
    <xacro:inertia_wheel />
    </link>
</robot>